### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by parthhadiya** [md-farhan-memon/Saavn-Downloader---Updated#2]
F:\Downloads\IDM\Compressed\Saavn-Downloader---Updated-master>python saavn_downloader.py https://www.saavn.com/s/album/hindi/Secret-Superstar-2017/YENaxXwvtyo_
Traceback (most recent call last):
  File "saavn_downloader.py", line 12, in <module>
    import eyed3
  File "C:\Python\lib\site-packages\eyed3\__init__.py", line 35, in <module>
    from .utils.log import log                                            # noqa
  File "C:\Python\lib\site-packages\eyed3\utils\__init__.py", line 27, in <module>
    import magic
  File "C:\Python\lib\site-packages\magic.py", line 176, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

**Comment by legowtham** [comment]
Try downgrading the eyeD3 to 0.8.0, cos, it has not dependency on libmagic. That worked for me.

**Comment by parthhadiya** [comment]
@ofgowtham 
Could not find the version that satisfies the requirement.
I tried pip install eyeD3 0.8.0 and also tried the zip file from source.

**Comment by legowtham** [comment]
pip install this https://goo.gl/EeuzDB 
Check this page https://testpypi.python.org/pypi/eyeD3/0.8.0a2

**Comment by parthhadiya** [comment]
Already tried this one, gives the same error
Could not find a version that satisfies the requirement setup.py (from versions: )
No matching distribution found for setup.py

**Comment by parthhadiya** [comment]
@ofgowtham
